#!/usr/bin/env bash

#Script to write hi in 9th index

count=0

until [ $count -eq 10 ]
do
	if [ $count -eq 9 ]
	then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi

	count=$((count+1))
done
